---
title: "Exploratory Data Analysis (new dataset)"
author: "Will Simmons"
date: "4/1/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)

data = readRDS('./data/new_analytic_dataset.RDS')
```

# Correlation Matrix

```{r, fig.width = 12, fig.height = 12}
data %>% 
  select(-ends_with("det"), -year, -id, -race, -sex) %>% 
  mutate(hh_income = as.numeric(hh_income)) %>% 
  cor() %>% 
  ggcorrplot::ggcorrplot(type = "lower",
                         colors = c("#ED6A5A", "#FFFFF9", "#36C9C6"),
                         show.diag = FALSE,
                         lab = TRUE,
                         lab_size = 2.5) +
                         labs(title = "Figure 1. Correlation matrix of outcome and features") +
                         theme(plot.title.position = "plot",
                               legend.position = "bottom")


```

# Distribution Function

```{r}
# Function
density_plot = function(.data, variable, xlab, title, caption, log_x) {
  
  # must pipe data into this function - allows for filtering out LOD values for relevant vars
  # filter(bpa_det == 0) %>% 
a =
  .data %>% 
  arrange({{variable}}) %>% 
  ggplot(aes(x = {{variable}})) +
  geom_density() +
  # scale_x_log10() +
  theme_bw() +
  labs(x = paste0(xlab),
       y = "Density",
       title = do.call("paste", c(title, sep = "\t")),
       caption = paste0(caption)
  ) +
  theme(plot.title = element_text(hjust = 0.5))  
  
  if (log_x == TRUE) {
    
    a + scale_x_log10()
    
  } else {
    
    a
    
  }
  
}
```

# Urinary Assay Distributions

```{r}
### Creating density plots with function above

# BPA
data %>% 
  filter(bpa_det == 0) %>% 
  density_plot(variable = bpa,
               xlab = "Urinary BPA (ng/mL)",
               title = list("Urinary BPA Distribution\nSample (n = ", nrow(data), ") from NHANES 2007-8"),
               caption = "*Sample above lower detection limit (0.2 ng/mL)",
               log_x = TRUE)

# 4-tert-octylphenol
data %>% 
  filter(tert_octylphenol_det == 0) %>% 
  density_plot(variable = tert_octylphenol,
               xlab = "Urinary 4-tert-4-octylphenol (ng/mL)",
               title = list("Urinary 4-tert-octylphenol Distribution\nSample (n = ", nrow(data), ") from NHANES 2007-8"),
               caption = "*Sample above lower detection limit (0.2 ng/mL)",
               log_x = TRUE)

# Benzophenone-3
data %>% 
  filter(benzophenone_3_det == 0) %>% 
  density_plot(variable = benzophenone_3,
               xlab = "Benzophenone-3 (ng/mL)",
               title = list("Urinary Benzophenone-3 Distribution\nSample (n = ", nrow(data), ") from NHANES 2007-8"),
               caption = "*Sample above lower detection limit (0.4 ng/mL)",
               log_x = TRUE)

# Triclosan
data %>% 
  filter(triclosan_det == 0) %>% 
  density_plot(variable = triclosan,
               xlab = "Urinary Triclosan (ng/mL)",
               title = list("Urinary Triclosan Distribution\nSample (n = ", nrow(data), ") from NHANES 2007-8"),
               caption = "*Sample above lower detection limit (2.3 ng/mL)",
               log_x = TRUE)

# Methyl Paraben
data %>% 
  filter(methyl_paraben_det == 0) %>% 
  density_plot(variable = methyl_paraben,
               xlab = "Urinary Methyl Paraben (ng/mL)",
               title = list("Urinary Methyl Paraben Distribution\nSample (n = ", nrow(data), ") from NHANES 2007-8"),
               caption = "*Sample above lower detection limit (1 ng/mL)",
               log_x = TRUE)

# Ethyl Paraben
data %>% 
  filter(ethyl_paraben_det == 0) %>% 
  density_plot(variable = ethyl_paraben,
               xlab = "Urinary Ethyl Paraben (ng/mL)",
               title = list("Urinary Ethyl Paraben Distribution\nSample (n = ", nrow(data), ") from NHANES 2007-8"),
               caption = "*Sample above lower detection limit (1 ng/mL)",
               log_x = TRUE)

# Propyl Paraben
data %>% 
  filter(propyl_paraben_det == 0) %>% 
  density_plot(variable = propyl_paraben,
               xlab = "Urinary Propyl Paraben (ng/mL)",
               title = list("Urinary Propyl Paraben Distribution\nSample (n = ", nrow(data), ") from NHANES 2007-8"),
               caption = "*Sample above lower detection limit (0.2 ng/mL)",
               log_x = TRUE)

# Butyl Paraben
data %>% 
  filter(butyl_paraben_det == 0) %>% 
  density_plot(variable = butyl_paraben,
               xlab = "Urinary Butyl Paraben (ng/mL)",
               title = list("Urinary Butyl Paraben Distribution\nSample (n = ", nrow(data), ") from NHANES 2007-8"),
               caption = "*Sample above lower detection limit (0.2 ng/mL)",
               log_x = TRUE)


# Creatinine
data %>% 
  density_plot(variable = creatinine,
               xlab = "Urinary creatinine (unitless)",
               title = list("Urinary Creatinine Distribution\nSample (n = ", nrow(data), ") from NHANES 2007-8"),
               caption = NULL,
               log_x = TRUE)

# TSH
data %>% 
  density_plot(variable = tsh,
               xlab = "Urinary TSH (uIU/mL)",
               title = list("Urinary TSH Distribution\nSample (n = ", nrow(data), ") from NHANES 2007-8"),
               caption = NULL,
               log_x = TRUE)


```

# Percent Over/Under LOD - Exposures

```{r}
  
  data %>% 
  pivot_longer(
    matches("det$"),
    names_to = "exposure",
    values_to = "lod"
  ) %>% 
  select(exposure, lod) %>% 
  mutate(
    exposure = str_replace(exposure, "_det", "")
  ) %>% 
  mutate(
    lod = as.factor(lod),
    lod = fct_recode(lod, 
                     "Above LOD" = "0",
                     "Below LOD" = "1")
  ) %>% 
  group_by(exposure, lod) %>% 
  summarize(count = n(),
            prev = n()/nrow(data)
  ) %>% 
  ggplot(aes(x = exposure, y = prev, fill = lod)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Exposure",
       y = "Proportion",
       title = "Proportion Above/Below LOD by Exposure",
       subtitle = "NHANES 2007-8") +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5)
  ) +
  scale_fill_brewer(palette = 3)

```

# Scatterplots

```{r}

scatter = function(predictor_string, outcome_string, log_x, log_y, smooth) {
  
  a = 
    ggplot(data = data,
           aes_string(x = predictor_string,
                      y = outcome_string)) +
    geom_point(alpha = 0.4, color = 'DarkGray')
  
  if (log_x == TRUE) {
    
    b = a + scale_x_log10()
    
  } else {
    
    b = a
    
  }
  
  if (log_y == TRUE) {
    
    c = b + scale_y_log10()
    
  } else {
    
    c = b
    
  }
  
  if (smooth == TRUE) {
    
    c + geom_smooth(method = "gam", 
                    se = FALSE,
                    color = 'IndianRed')
    
  } else {
    
    c
    
  }
    
  
}

# Cairo::CairoWin()

# # Test
# scatter(predictor_string = 'bpa_creatinine',
#         outcome_string = 'peroxidase_antibodies',
#         log_x = TRUE,
#         log_y = TRUE,
#         smooth = TRUE)


```

## List of predictors, outcomes for grid of scatters

```{r}

exposure_list_creatinine =
  data %>% 
  select(ends_with("_creatinine")) %>% 
  names() %>% 
  as_tibble() %>% 
  rename(predictor_string = value) %>% 
  mutate(predictor_string = as.character(predictor_string))

outcome_list =
  data %>% 
  select(8:15) %>% 
  names() %>% 
  as_tibble() %>% 
  rename(outcome_string = value) %>% 
  mutate(outcome_string = as.character(outcome_string))
  # cols 8-15

scatter_grid =
  expand_grid(
    exposure_list_creatinine,
    outcome_string = "tsh",
    # outcome_string = c("t3_free", "tsh"),
    log_x = TRUE,
    log_y = FALSE,
    smooth = TRUE
  )

```

## Map over list

```{r}

scatter_plots =
  pmap(scatter_grid, scatter)

cowplot::plot_grid(plotlist = scatter_plots,
                   ncol = 4)

```

