---
title: "Logistic + Nonlinear Analysis"
author: "Will Simmons"
date: "3/24/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}

library(tidyverse)
library(conflicted)

data = readRDS('./data/analytic_dataset.RDS')

```

# 1. Crude logistic regression models

```{r}
# Creating function to run univariable logistic regression
uni_logistic = function(predictor) {
  
  glm(reformulate(as.character(predictor),
                  'thyroid_outcome'),
      data = data,
      family = 'binomial') %>% 
  
  broom::tidy()
  
}

# Example
# uni_logistic("bpa_u")
```

```{r}
# List of covariate names to map over
all_variables =
  data %>% 
  select(
    -year,
    -id,
    -ends_with("_det"),
    -thyroid_outcome
  ) %>% 
  names() %>% 
  as.list()

# Dataframe of univariable logistic regression models
uni_results =
  map_dfr(all_variables, uni_logistic)

```

# 2. Adjusted logistic regression models

```{r}
# Covariate/confounder set
covariates =
  c(
    "sex",
    "age",
    "race",
    "year",
    
    "creatinine_u"
  )
  
# Exposure set
exposures =
  

```


# 3. Crude nonlinear models

# 4. Adjusted nonlinear models

